// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayer.REPOSITORY;

#nullable disable

namespace NLayer.REPOSITORY.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayer.CORE.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(616),
                            Name = "Pencils"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(674),
                            Name = "Notebooks"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(677),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("NLayer.CORE.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("height")
                        .HasColumnType("int");

                    b.Property<int>("width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("productFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            ProductId = 1,
                            height = 8,
                            width = 3
                        },
                        new
                        {
                            Id = 2,
                            Color = "Purple",
                            ProductId = 4,
                            height = 25,
                            width = 15
                        });
                });

            modelBuilder.Entity("NLayer.CORE.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriesId = 1,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1158),
                            Name = "Pencil 1",
                            Price = 143m,
                            Stock = 520
                        },
                        new
                        {
                            Id = 2,
                            CategoriesId = 1,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1170),
                            Name = "Pencil 2",
                            Price = 345m,
                            Stock = 127
                        },
                        new
                        {
                            Id = 3,
                            CategoriesId = 1,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1181),
                            Name = "Pencil 3",
                            Price = 52m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 4,
                            CategoriesId = 2,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1248),
                            Name = "Notebook 1",
                            Price = 69m,
                            Stock = 142
                        },
                        new
                        {
                            Id = 5,
                            CategoriesId = 2,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1254),
                            Name = "Notebook 2",
                            Price = 48m,
                            Stock = 326
                        },
                        new
                        {
                            Id = 6,
                            CategoriesId = 2,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1257),
                            Name = "Notebook 3",
                            Price = 140m,
                            Stock = 399
                        },
                        new
                        {
                            Id = 7,
                            CategoriesId = 3,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1260),
                            Name = "Book 1",
                            Price = 115m,
                            Stock = 550
                        },
                        new
                        {
                            Id = 8,
                            CategoriesId = 3,
                            CreatedDate = new DateTime(2022, 3, 30, 17, 42, 18, 467, DateTimeKind.Local).AddTicks(1268),
                            Name = "Book 2",
                            Price = 265m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("NLayer.CORE.ProductFeature", b =>
                {
                    b.HasOne("NLayer.CORE.Products", "Products")
                        .WithOne("ProductFeature")
                        .HasForeignKey("NLayer.CORE.ProductFeature", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.CORE.Products", b =>
                {
                    b.HasOne("NLayer.CORE.Categories", "category")
                        .WithMany("Products")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("NLayer.CORE.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NLayer.CORE.Products", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
